# -*- mode: ruby -*-
# vi: set ft=ruby :

############### 我的工程模板 ##############

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

    # 启动超时100秒
    config.vm.boot_timeout = 100
    config.vm.box_check_update = false

    # 登录相关
    config.ssh.username = "lidong"
    # 不安全， 不建议使用
    # config.ssh.password = "1"
    # config.ssh.insert_key = true
    config.ssh.private_key_path = "~/.ssh/id_rsa"
    # config.ssh.forward_agent = true

    (1..5).each do |i|
        config.vm.define "node#{i}" do |node|
            # 启动的虚拟box
            node.vm.box = "hadoopv2"

            # 主机名
            node.vm.hostname = "node#{i}"

            # 修改NAT网卡的mac
            node.vm.base_mac = "080027d507f#{i}"

            # 设置eth0 IP, mac地址
            node.vm.network "public_network", ip: "192.168.1.20#{i}", :bridge => 'eth0', :mac => "08002722a10#{i}"

            # VirtaulBox相关配置
            node.vm.provider "virtualbox" do |v|
                # 设置虚拟机的名称
                v.name = "node#{i}"
                # 设置虚拟机的内存大小
                v.memory = 512
                # 设置虚拟机的CPU个数
                v.cpus = 1
            end
        end
    end

    if File.file?('remote')
        config.vm.synced_folder "remote", "/home/lidong/hadoop", owner: "lidong", group: "lidong"
        config.vm.provision "shell", path: "remote/script.sh"
    end
end
