(clear)
(watch compilations)
(load global.clp)
(load func.clp)
(load main.clp)
(load urine.clp)
(load opt-daily.clp)
(load gender.clp)
(load weight.clp)
(load condition.clp)
(load exercise.clp)
(reset)
(run)
