
all:
	# g++ -std=c++11 -o out_c11_04 ./c11_04.cpp
	g++ -std=c++11 -o out_c11_15 ./c11_15.cpp
	# g++ -std=c++11 -o out_c11_17 ./c11_17.cpp
	# g++ -std=c++11 -o out_c11_27 ./c11_27.cpp
	# g++ -std=c++11 -o out_c11_28 ./c11_28.cpp

clean:
	rm ./out_*
